# Generated by Django 4.0 on 2021-12-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('datepub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
