# Generated by Django 4.0 on 2021-12-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='datepub',
            field=models.DateTimeField(),
        ),
    ]
