# Generated by Django 4.0 on 2021-12-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_userregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregion',
            name='region',
            field=models.CharField(choices=[('Адлер', 'АДЛЕР'), ('Сочи', 'СОЧИ'), ('Туапсе', 'ТУАПСЕ'), ('Лазаревская', 'ЛАЗАРЕВСКАЯ')], default='Адлер', max_length=15),
        ),
    ]
