# Generated by Django 4.0 on 2022-02-20 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_userregion_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterModelOptions(
            name='userregion',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.reports')),
            ],
        ),
    ]
