# Generated by Django 4.0 on 2022-04-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_reports_options_alter_userregion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
