# Generated by Django 3.0 on 2022-04-08 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('a', 'Адлер'), ('s', 'Сочи'), ('t', 'Туапсе'), ('l', 'Лазаревская')], default='a', max_length=1, verbose_name='Регион')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Данные бригадира',
                'verbose_name_plural': 'Данные бригадиров',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отчёта')),
                ('datepub', models.DateField(verbose_name='Дата создания отчёта')),
                ('timepub', models.TimeField(verbose_name='Время создания отчёта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бригадир')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['datepub', 'timepub'],
                'get_latest_by': ['datepub', 'timepub'],
                'unique_together': {('author', 'text', 'timepub')},
            },
        ),
    ]
